kind: pipeline
name: default

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - pip install -r dev-requirements.txt
  - which make || apk add make
  - make test
- name: build
  image: python:3.7-alpine
  commands:
  - which make || apk add make
  - pip install -r dev-requirements.txt
  - make build
- name: upload
  image: python:3.7-alpine
  environment:
    TWINE_USERNAME:
      from_secret: TWINE_USERNAME
    TWINE_PASSWORD:
      from_secret: TWINE_PASSWORD
  commands:
  - which make || apk add make
  - pip install -r dev-requirements.txt
  - make upload
  when:
    event:
    - tag
