ARG ALPINE_VERSION=3.23

# Builder stage
FROM alpine:${ALPINE_VERSION} as builder

# build dependencies
RUN apk add --no-cache \
  py3-hatchling \
  py3-hatch-vcs \
  py3-flake8 \
  py3-pytest \
  twine \
  git \
  sccache \
  just \
  openssl-dev

ENV RUSTC_WRAPPER=/usr/bin/sccache

WORKDIR /app
