[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "cloudbender"
dynamic = ["version"]
authors = [
  { name="Stefan Reimer", email="stefan@zero-downtime.net" },
]
description = "Deploy and maintain infrastructure in automated and trackable manner"
readme = "README.md"
license = "AGPL-3.0-or-later"
requires-python = ">=3.9"
dependencies = [
        "boto3==1.34.88",
        "mock==5.1.0",
        "Jinja2==3.1.3",
        "click==8.1.7",
        "pexpect==4.9.0",
        "python-minifier==2.9.0",
        "cfn-lint==0.86.3",
        "ruamel.yaml==0.18.6",
        "pulumi==3.113.3",
        "pulumi-aws==6.32.0",
        "pulumi-aws-native==0.102.0",
        "pulumi-policy==1.11.0",
        "pulumi-command==0.10.0",
        ]

classifiers = [
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Operating System :: POSIX",
        "Programming Language :: Python",
        "License :: OSI Approved :: GNU Affero General Public License v3",
]

[project.optional-dependencies]
tests = [
  'flake',
  'pytest',
  'twine',
]

[project.urls]
"Homepage" = "https://git.zero-downtime.net/ZeroDownTime/CloudBender"

[project.scripts]
cloudbender = "cloudbender.cli:cli"

[tool.hatch.version]
source = "vcs"

[tool.isort]
profile = "black"

